spring.application.name=teste
server.port=${PORT:8080}
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração opcional do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect